name: Build Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List workspace
        run: ls -R .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install correct Jupyter Book
        run: |
          pip uninstall -y mystmd myst-cli || true
          pip install jupyter-book==0.15.1

      - name: Build the book
        run: jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-html
          path: _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
